# Prometheus Alert Rules for Raspberry Pi
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: raspberry-pi-alerts
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: kube-prometheus-stack
spec:
  groups:
    - name: raspberry-pi.rules
      rules:
        # High CPU Usage
        - alert: HighCPUUsage
          expr: 100 - (avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 70
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage detected"
            description: "CPU usage is above 70% for more than 10 minutes. Current value: {{ $value }}%"

        # High Memory Usage
        - alert: HighMemoryUsage
          expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 80
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High memory usage detected"
            description: "Memory usage is above 80% for more than 5 minutes. Current value: {{ $value }}%"

        # High Temperature
        - alert: HighTemperature
          expr: node_hwmon_temp_celsius > 75
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "High CPU temperature detected"
            description: "CPU temperature is above 75°C. Current value: {{ $value }}°C"

        # Disk Space Low
        - alert: DiskSpaceLow
          expr: (1 - (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"})) * 100 > 85
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Disk space running low"
            description: "Root filesystem usage is above 85%. Current value: {{ $value }}%"

        # USB Storage Low
        - alert: USBStorageLow
          expr: (1 - (node_filesystem_avail_bytes{mountpoint="/mnt/usb-data"} / node_filesystem_size_bytes{mountpoint="/mnt/usb-data"})) * 100 > 90
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "USB storage space critically low"
            description: "USB storage usage is above 90%. Current value: {{ $value }}%"

    - name: kubernetes.rules
      rules:
        # Pod Restart Burst
        - alert: PodRestartBurst
          expr: increase(kube_pod_container_status_restarts_total[1h]) > 5
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: "Pod restarting frequently"
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has restarted {{ $value }} times in the last hour"

        # Pod Not Ready
        - alert: PodNotReady
          expr: kube_pod_status_ready{condition="false"} == 1
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "Pod not ready"
            description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready state for more than 15 minutes"

        # Deployment Replica Mismatch
        - alert: DeploymentReplicaMismatch
          expr: kube_deployment_spec_replicas != kube_deployment_status_available_replicas
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "Deployment replica mismatch"
            description: "Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has {{ $labels.spec_replicas }} desired but {{ $labels.available_replicas }} available replicas"

        # PVC Usage High
        - alert: PVCUsageHigh
          expr: (kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes) * 100 > 85
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "PVC usage high"
            description: "PVC {{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} usage is above 85%. Current value: {{ $value }}%"

    - name: application.rules
      rules:
        # High HTTP Error Rate
        - alert: HighHTTPErrorRate
          expr: (sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m]))) * 100 > 5
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High HTTP 5xx error rate"
            description: "HTTP 5xx error rate is above 5% for more than 5 minutes. Current value: {{ $value }}%"

        # Application Down
        - alert: ApplicationDown
          expr: up{job="sample-backend"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Application is down"
            description: "Sample application backend has been down for more than 1 minute"

        # Database Connection Issues
        - alert: DatabaseConnectionIssues
          expr: database_connections_active < 1
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Database connection issues"
            description: "No active database connections detected for more than 5 minutes"

    - name: storage.rules
      rules:
        # Persistent Volume Issues
        - alert: PersistentVolumeIssues
          expr: kube_persistentvolume_status_phase{phase!="Available",phase!="Bound"} == 1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Persistent Volume issues"
            description: "PV {{ $labels.persistentvolume }} is in {{ $labels.phase }} state"
