apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/k3s-argocd-rasp-pi.git
    path: apps/helm/sample-app
    targetRevision: HEAD
    helm:
      values: |
        frontend:
          service:
            type: NodePort
            nodePort: 30080
        backend:
          service:
            type: NodePort
            nodePort: 30081
        ingress:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true