---
- name: Download Argo CD manifests
  get_url:
    url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    dest: /tmp/argocd-install.yaml

- name: Apply Argo CD manifests
  kubernetes.core.k8s:
    src: /tmp/argocd-install.yaml
    state: present
    wait: true
    wait_timeout: 600

- name: Wait for Argo CD server to be ready
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: argocd-server
    namespace: argocd
    wait: true
    wait_condition:
      type: Available
      status: "True"
    wait_timeout: 600

- name: Get Argo CD admin password
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: argocd-initial-admin-secret
    namespace: argocd
  register: argocd_secret

- name: Display Argo CD admin password
  debug:
    msg: "Argo CD admin password: {{ argocd_secret.resources[0].data.password | b64decode }}"
  when: argocd_secret.resources | length > 0