---
- name: Download k3s install script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: '0755'

- name: Install k3s with ARM64 optimizations
  shell: |
    INSTALL_K3S_VERSION={{ k3s_version }} \
    INSTALL_K3S_EXEC="--disable traefik --disable servicelb --write-kubeconfig-mode 644" \
    /tmp/k3s-install.sh
  args:
    creates: /usr/local/bin/k3s

- name: Wait for k3s to be ready
  wait_for:
    port: 6443
    host: localhost
    timeout: 300

- name: Copy kubeconfig for current user
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ ansible_env.HOME }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_env.USER }}"
    mode: '0600'

- name: Create .kube directory if it doesn't exist
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    owner: "{{ ansible_env.USER }}"
    mode: '0755'
  become: no