---
- name: Check if USB device exists
  stat:
    path: /dev/sda1
  register: usb_device

- name: Create USB mount directory
  file:
    path: "{{ usb_mount_point }}"
    state: directory
    mode: '0755'

- name: Mount USB storage
  mount:
    path: "{{ usb_mount_point }}"
    src: /dev/sda1
    fstype: ext4
    opts: defaults
    state: mounted
  when: usb_device.stat.exists

- name: Create storage directories
  file:
    path: "{{ usb_mount_point }}/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - postgres
    - prometheus
    - loki
    - velero