{{- if .Values.frontend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-app.fullname" . }}-frontend
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: {{ .Values.frontend.service.name }}
  selector:
    {{- include "sample-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}

{{- if .Values.backend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-app.fullname" . }}-backend
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.backend.service.port }}"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: {{ .Values.backend.service.name }}
  selector:
    {{- include "sample-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}

{{- if .Values.database.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-app.fullname" . }}-postgres
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.targetPort }}
      protocol: TCP
      name: {{ .Values.database.service.name }}
  selector:
    {{- include "sample-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}

# Service aliases for easier reference
{{- if .Values.frontend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: {{ .Values.frontend.service.name }}
  selector:
    {{- include "sample-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}

{{- if .Values.backend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.backend.service.port }}"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: {{ .Values.backend.service.name }}
  selector:
    {{- include "sample-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}

{{- if .Values.database.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.targetPort }}
      protocol: TCP
      name: {{ .Values.database.service.name }}
  selector:
    {{- include "sample-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}